import psycopg2

# Conectar a la base de datos existente 'postgres'
connection = psycopg2.connect(
    host="localhost",       # Cambia si tu base de datos no está en localhost
    port="5432",            # Cambia si usas otro puerto
    user="postgres",        # Usuario de PostgreSQL
    password="9893",        # Contraseña de PostgreSQL
    database="postgres"     # Nombre de la base de datos
)
cursor = connection.cursor()

# Crear la tabla 'countries' dentro de la base de datos 'postgres'
create_table_query = '''
CREATE TABLE IF NOT EXISTS countries (
    country_name VARCHAR(100) PRIMARY KEY,
    continent_name VARCHAR(100)
);
'''
cursor.execute(create_table_query)
connection.commit()

# Lista de países y continentes
countries_and_continents = [
    ("Afghanistan", "Asia"),
    ("Albania", "Europe"),
    ("Algeria", "Africa"),
    ("Angola", "Africa"),
    ("Antigua and Barbuda", "North America"),
    ("Argentina", "South America"),
    ("Armenia", "Asia"),
    ("Australia", "Australia"),
    ("Austria", "Europe"),
    ("Azerbaijan", "Asia"),
    ("Barbados", "North America"),
    ("Belarus", "Europe"),
    ("Belgium", "Europe"),
    ("Benin", "Africa"),
    ("Bermuda", "North America"),
    ("Bolivia", "South America"),
    ("Bosnia-Herzegovina", "Europe"),
    ("Botsuana", "Africa"),
    ("Brazil", "South America"),
    ("Bulgaria", "Europe"),
    ("Burkina Faso", "Africa"),
    ("Burundi", "Africa"),
    ("Cameroon", "Africa"),
    ("Canada", "North America"),
    ("Cape Verde", "Africa"),
    ("Central African Republic", "Africa"),
    ("Chad", "Africa"),
    ("Chile", "South America"),
    ("China", "Asia"),
    ("Chinese Taipei", "Asia"),
    ("Colombia", "South America"),
    ("Comoros", "Africa"),
    ("Congo", "Africa"),
    ("Costa Rica", "North America"),
    ("Cote d'Ivoire", "Africa"),
    ("Croatia", "Europe"),
    ("Cuba", "North America"),
    ("Curacao", "North America"),
    ("Cyprus", "Europe"),
    ("Czech Republic", "Europe"),
    ("Denmark", "Europe"),
    ("Dominica", "North America"),
    ("Dominican Republic", "North America"),
    ("DR Congo", "Africa"),
    ("Ecuador", "South America"),
    ("Egypt", "Africa"),
    ("England", "Europe"),
    ("Equatorial Guinea", "Africa"),
    ("Eritrea", "Africa"),
    ("Estonia", "Europe"),
    ("Ethiopia", "Africa"),
    ("Faroe Islands", "Europe"),
    ("Finland", "Europe"),
    ("France", "Europe"),
    ("French Guiana", "South America"),
    ("Gabon", "Africa"),
    ("Georgia", "Asia"),
    ("Germany", "Europe"),
    ("Ghana", "Africa"),
    ("Gibraltar", "Europe"),
    ("Greece", "Europe"),
    ("Grenada", "North America"),
    ("Guadeloupe", "North America"),
    ("Guatemala", "North America"),
    ("Guernsey", "Europe"),
    ("Guinea", "Africa"),
    ("Guinea-Bissau", "Africa"),
    ("Guyana", "South America"),
    ("Haiti", "North America"),
    ("Honduras", "North America"),
    ("Hongkong", "Asia"),
    ("Hungary", "Europe"),
    ("Iceland", "Europe"),
    ("India", "Asia"),
    ("Indonesia", "Asia"),
    ("Iran", "Asia"),
    ("Iraq", "Asia"),
    ("Ireland", "Europe"),
    ("Israel", "Asia"),
    ("Italy", "Europe"),
    ("Jamaica", "North America"),
    ("Japan", "Asia"),
    ("Jordan", "Asia"),
    ("Kazakhstan", "Asia"),
    ("Kenya", "Africa"),
    ("Korea, South", "Asia"),
    ("Kosovo", "Europe"),
    ("Kyrgyzstan", "Asia"),
    ("Latvia", "Europe"),
    ("Lebanon", "Asia"),
    ("Liberia", "Africa"),
    ("Libya", "Africa"),
    ("Liechtenstein", "Europe"),
    ("Lithuania", "Europe"),
    ("Luxembourg", "Europe"),
    ("Madagascar", "Africa"),
    ("Malawi", "Africa"),
    ("Mali", "Africa"),
    ("Malta", "Europe"),
    ("Martinique", "North America"),
    ("Mauritania", "Africa"),
    ("Mauritius", "Africa"),
    ("Mexico", "North America"),
    ("Moldova", "Europe"),
    ("Monaco", "Europe"),
    ("Montenegro", "Europe"),
    ("Montserrat", "North America"),
    ("Morocco", "Africa"),
    ("Mozambique", "Africa"),
    ("N/A", "Unknown"),
    ("Namibia", "Africa"),
    ("Netherlands", "Europe"),
    ("New Zealand", "Australia"),
    ("Niger", "Africa"),
    ("Nigeria", "Africa"),
    ("North Macedonia", "Europe"),
    ("Northern Ireland", "Europe"),
    ("Norway", "Europe"),
    ("Pakistan", "Asia"),
    ("Palestine", "Asia"),
    ("Panama", "North America"),
    ("Paraguay", "South America"),
    ("Peru", "South America"),
    ("Philippines", "Asia"),
    ("Poland", "Europe"),
    ("Portugal", "Europe"),
    ("Qatar", "Asia"),
    ("Réunion", "Africa"),
    ("Romania", "Europe"),
    ("Russia", "Europe"),
    ("Rwanda", "Africa"),
    ("Saint-Martin", "North America"),
    ("Sao Tome and Principe", "Africa"),
    ("Saudi Arabia", "Asia"),
    ("Scotland", "Europe"),
    ("Senegal", "Africa"),
    ("Serbia", "Europe"),
    ("Sierra Leone", "Africa"),
    ("Slovakia", "Europe"),
    ("Slovenia", "Europe"),
    ("South Africa", "Africa"),
    ("Southern Sudan", "Africa"),
    ("Spain", "Europe"),
    ("St. Kitts & Nevis", "North America"),
    ("St. Vincent & Grenadinen", "North America"),
    ("Suriname", "South America"),
    ("Sweden", "Europe"),
    ("Switzerland", "Europe"),
    ("Syria", "Asia"),
    ("Tahiti", "Oceania"),
    ("Tajikistan", "Asia"),
    ("The Gambia", "Africa"),
    ("Togo", "Africa"),
    ("Trinidad and Tobago", "North America"),
    ("Tunisia", "Africa"),
    ("Türkiye", "Asia"),
    ("Turkmenistan", "Asia"),
    ("Uganda", "Africa"),
    ("Ukraine", "Europe"),
    ("United States", "North America"),
    ("Uruguay", "South America"),
    ("Uzbekistan", "Asia"),
    ("Venezuela", "South America"),
    ("Vietnam", "Asia"),
    ("Wales", "Europe"),
    ("Yugoslavia (Republic)", "Europe"),
    ("Zambia", "Africa"),
    ("Zimbabwe", "Africa")
]

# Insertar los datos en la tabla 'countries'
insert_query = "INSERT INTO countries (country_name, continent_name) VALUES (%s, %s) ON CONFLICT (country_name) DO NOTHING;"
cursor.executemany(insert_query, countries_and_continents)
connection.commit()

# Cerrar la conexión
cursor.close()
connection.close()

print("Datos insertados exitosamente en la tabla 'countries'.")